--- # My First Yaml Playbook for Ansible
- hosts: apachehosts
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    -  name: web_domian
       prompt: Web Domain
  tasks:
    - name: Install git Version Control
      action: yum name=lynx state=latest update_cache=true
    - name: Check for Telnet client
      action: yum name=telnet state=absent
    - name: yum name= Install Git
      action: yum pkg=git state=latest update_cache=true 
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted 

