- name: Install Apache Web Server specific to the distribution type(RedHat/CentOS)
  yum: pkg={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat'"
  notify: Restart HTTPD
- name: Install Apache Web Servre Specific to the Distribution type(Debian)
  apt: pkg={{ debian_apache }} state=latest
  when: "ansible_os_family == 'Debian'"
  notify: Restart apache2

