- name: Restart HTTPD 
  service: name={{ redhat_apache }} state=restarted
  when: "ansible_os_family == 'RedHat'"
- name: Restart apache2
  service: name={{ debian_apache }} state=restarted
  when: " ansible_os_family == 'Debian'"
  ignore_errors: yes

