--- # Installing packages based on Distributions
- hosts: apachehosts
  user: test
  connection: ssh
  sudo: yes
  gather_facts: no
  tasks:
   - name: Installing packege specific to CentOs and Redhat
     yum: pkg=httpd state=latest
     when: ansible_os_family == "RedHat"
   - name: Installing the package specific to Debian Distribution
     apt: pkg=apache2 state=latest
     when: ansible_os_family == "Debian"
  # - setup:
   #    filter: ansible_*
   - name: starting the httpd service
     service: name=httpd state=started
     when: ansible_os_family == "RedHat"
   - name: starting apache2 service
     service: name=apache2 state=started
     when: ansible_os_family == "Debian" 
