--- # deligate to Function 
- hosts: myhosts
  user: test
  sudo: yes
  connection: ssh
  tasks:
    - name: Run a remote ping on the application server
      command: ping -c 4 rajaunix4 > /home/test/Playbooks/Ping1.out
      delegate_to: 127.0.0.1
    - name: Install package
      apt: pkg=lynx state=latest 
