--- # Error Handing
- hosts: myhosts
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command that will fail
      command: /bin/false
      ignore_errors: yes
    - name: Install Telnet
      yum: pkg=telnet state=latest
