--- # Full Include Task example
- hosts: myhosts
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
    - include: plays/packages.yml
    - name: Verify the telnet package instaled
      raw: yum list installed | grep telnet > /home/test/pkgs.log
