--- # MONGODB INSTALLATION
- hosts: myhosts
  connection: ssh
  sudo: yes
  gather_facts: yes
  tasks: 
 # -  name: Creating the MONGODB Repos directory
 #    command: touch /etc/yum.repos.d/mongodb-org-2.6.repo
 # -  name: Installing the MongoDB from baseUrl
  #   get_url: url=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/  dest=/etc/yum.repos.d/mongodb-org-2.6.repo  
  

  - name: Installing the Mongodb package
    yum: pkg=mongodb-org state=installed

