--- # Service Module Example
- hosts: myhosts
  user: test
  connection: ssh
  sudo: yes
  tasks:
  - name: Install Web Server
    action: yum name=httpd state=installed
  - name: Start the web server
    service: name=httpd state=started
  - name: Enable Httpd After Reboot
    service: name=httpd enabled=yes
