--- # TAG for Playbook
- hosts: myhosts
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
    - name: Install telnet and lynx packages
      yum: pkg={{ item }} state=latest
      with_items: 
        - telnet
        - lynx
      tags: 
        - pacakge
    - name: Verify that telnet was installed
      raw: yum list installed|grep telnet > /home/test/pkg.log
      tags: 
        - verification


